### ISSUE TITLE
Modeline color is inconsistent when using helm

### ISSUE THREAD

**Issue by Wojtek242** [seagle0128/doom-modeline#114]
**Describe**
When using Helm commands, the modeline color is inconsistent.

This is what my modeline looks like normally
![good](https://user-images.githubusercontent.com/17829810/52533351-e5e33c00-2d32-11e9-891d-0a46a11ec049.png)

And this happens when I use helm
![bad](https://user-images.githubusercontent.com/17829810/52533357-027f7400-2d33-11e9-8a13-932f30d1bd72.png)

Notice, how the modeline is mixture of active/inactive faces.

I am aware that you are not a Helm user so I do not expect you to fix it, but I'm a bit stuck myself as to what is causing this. Do you think you could give me some pointers as to which doom-modeline faces I might need to play with or change? I'm happy to dig into code and spend time trying to figure it out.

**Steps and Expected**
Run `helm-command`.

**Environment:**
 - OS: Linux
 - Version Ubuntu 18.04
 - Package version 20190204

**Comment by seagle0128** [comment]
I think you need to check `helm-display-mode-line` and related codes. In `doom-modeline`, all faces are defined in `doom-modeline-core.el`.

**Comment by Wojtek242** [comment]
So I've had a bit of a look around and it seems that the inconsistency comes from the fact that when `helm-command` is active, `doom-modeline--active` flags the other buffers as inactive (which sounds like the correct thing to do), but the parts of the modeline that do not explicitly check whether the modeline is active, will display with the active colours.

For example, in the `buffer-info` segment if one removes the `if active` check in the code under the comment `;; buffer file name` and just leaves `name`:
```
(when-let ((name (or doom-modeline--buffer-file-name
                          (doom-modeline-update-buffer-file-name))))
       name)
```
it will display as active, consistently with the rest of the modeline.

I think the correct solution is to ensure that the entire modeline displays as inactive as this sounds like the most correct behaviour. I will have a look at how to achieve this. Perhaps helm has to be changed to make it display the modeline as inactive when the helm buffer is open.

**Comment by seagle0128** [comment]
Hmm, maybe you could implement helm segments for `doom-modeline` and submit a PR 😄 
As I mentioned in https://github.com/seagle0128/doom-modeline/issues/75#issuecomment-449927864.

**Comment by Wojtek242** [comment]
I think this is unrelated to the other issue, and sadly I don't have the time to implement a full helm segments as much as I'd like to :(

My issue looks like it is due to helm making all buffers current when the helm buffer is active, see https://github.com/emacs-helm/helm/issues/1579#issuecomment-250226641, but doom-modeline treats them as inactive.

A workaround that makes things visually consistent is to redefine the following function in my config:
```
(defun doom-modeline--active ()
  "Whether is an active window."
  t)
```
This will treat all windows in the current frame as active when the helm buffer is open, but otherwise seems to behave as expected.

It seems that doom-modeline and helm want two different things when the helm buffer is active and given what was said in the issue I linked it's unlikely helm will change. I will try to find some time to figure which part of helm makes all the windows active and somehow make doom-modeline account for that fact.

**Comment by seagle0128** [comment]
Good thinking but it's not the solution. `helm` buffers are very strange to make all windows **active**.  Have to specify active and inactive faces for all segments.

**Comment by seagle0128** [comment]
Another workaround is redefining `helm-display-mode-line`.

```elisp
(defun helm-display-mode-line (source &optional force)
  )
```

**Comment by seagle0128** [comment]
Another workaround. Please try.

```elisp
(add-hook 'helm-minibuffer-set-up-hook
          (lambda ()
            (advice-add #'doom-modeline--active :override (lambda () t))))
(add-hook 'helm-cleanup-hook
          (lambda ()
            (advice-remove #'doom-modeline--active (lambda () t))))
```

**Comment by seagle0128** [comment]
This issue is triggered by using minibuffers. I made the enhancements and close it. The most of segments look fine while using helm, except some spaces. I think it's a minor issue and won't fix that. Please test.

**Comment by Wojtek242** [comment]
Awesome! Looks better now! Thanks for all your work!

I now have a different minor issue:
![ok](https://user-images.githubusercontent.com/17829810/52589552-63946e00-2e3f-11e9-912c-5ae0439f4c7f.png)
See the Emacs icon on the left of the path.

But I can probably figure this one out myself at some point. Thanks again!

**Comment by seagle0128** [comment]
I committed some changes including fixing icons issue a few minutes ago. Please update and try later.

**Comment by aaronjensen** [comment]
FYI, even after these fixes I still see this all of the time when using magit and/or which-key and/or ivy.

**Comment by seagle0128** [comment]
@aaronjensen Would you please provide more details? e.g. Emacs version, doom-modeline version, screenshots, recordings,  etc.

I couldn't reproduce with `magit`, `which-key` and `ivy`.

**Comment by aaronjensen** [comment]
Seems to happen when I open magit and then `b b` to open the branch picker.

![doom](https://user-images.githubusercontent.com/8588/52864473-1b9b7280-30ef-11e9-9d52-6af390d5c054.gif)

Emacs version:

```
GNU Emacs 27.0.50 (build 1, x86_64-apple-darwin18.2.0, NS appkit-1671.20 Version 10.14.3 (Build 18D109)) of 2019-02-14
```

Doom modeline version: 20190212.1647

**Comment by seagle0128** [comment]
@aaronjensen Please upgrade to the latest version `20190214.1226` and retry. No issue in my env.

![image](https://user-images.githubusercontent.com/140797/52868003-31f00f80-317d-11e9-8982-3969e038d7b9.png)

**Comment by aaronjensen** [comment]
Oh, I must have upgraded too quickly after you pushed the fix. Sorry about the noise! It seems to work now. Cheers.

**Comment by aaronjensen** [comment]
Actually, I still see it in some cases on my work machine (Doom modeline is up to date)

In this case, it's happening every time I switch windows from a magit buffer to a non-magit buffer with `other-window`

![image](https://user-images.githubusercontent.com/8588/52880344-8e6c1400-3116-11e9-837e-194f1c71e2ae.png)

**Comment by seagle0128** [comment]
Unfortunately I couldn't reproduce it with the latest version in my local env.

**Comment by aaronjensen** [comment]
Okay, I see it all the time. Any tips on debugging?

**Comment by aaronjensen** [comment]
Oh, actually I have one custom part that's memoized and I see a problem there. I'll fix that and report back if I still see issues. Sorry for the trouble.

**Comment by aaronjensen** [comment]
Okay, so the problem I'm having is with `buffer-info`, and that's not my memoization. It appears that the last form, which looks like this:

```elisp
(when-let ((name (or doom-modeline--buffer-file-name
                          (doom-modeline-update-buffer-file-name))))
       (if active
           name
         (propertize name 'face 'mode-line-inactive)))
```

is the problem for me. If I change it to:

```elisp
(when-let ((name (or doom-modeline--buffer-file-name
                          (doom-modeline-update-buffer-file-name))))
       (if active
           (propertize name 'face 'doom-modeline-buffer-file)
         (propertize name 'face 'mode-line-inactive)))
```

Then it works. The contents of `doom-modeline--buffer-file-name` are sometimes propertized with `mode-line-inactive`, which makes sense because that's what `doom-modeline-update-buffer-file-name does. Perhaps the `face` propertization should be removed from that function and only `buffer-info` should do it?

**Comment by seagle0128** [comment]
@aaronjensen Thank you for the digging out! But I don't think it's the solution. The buffer name may contain a several faces, not only `doom-modeline-buffer-file`. I guess `doom-modeline--buffer-file-name` is not updated correctly in your case, but I was unable to figure out which case.

**Comment by aaronjensen** [comment]
If it helps, I believe it only happens on non-file-backed buffers like org agenda/magit/`*Messages*`. They start out inactive and no amount of switching to their window triggers a `doom-modeline-update-buffer-file-name`. If I trigger that manually, then it is correct.

**Comment by aaronjensen** [comment]
Okay, I can repro it consistently in this way:

1. Restart emacs
2. Open org agenda (for me, this takes some time because I have org lazy loaded. It needs to take time, I believe).
3. Switch away from Emacs (focus another app) while the agenda is opening
4. Wait for the agenda to load. It should appear inactive.
5. Focus emacs.

I added `(message "%s active: %S" (buffer-name) (doom-modeline--active))` to `doom-modeline-update-buffer-file-name` and I saw this:


```
*Org Agenda( )* active: t [54 times]
Rebuilding agenda buffer...
*Org Agenda( )* active: nil [55 times]
Rebuilding agenda buffer...done
```

It never runs again for Org Agenda.

Perhaps `doom-modeline-update-buffer-file-name` needs to be added as advice to `after-focus-change-function`? That may be emacs 27 specific, for older emacs, `focus-in-hook` should probably be used. Though I tried both of these and they didn't appear to help.

As an aside, I wonder if doing the work to calculate the buffer file name with memoization rather than attempting to use hooks would be better? That's what I'm doing in my custom segments and though error prone, it seems less fragile than having to think through all of the hooks that could make changes.

Here's an example:

```elisp
(defmemoize aj/formatted-buffer-project-name (file-name active)
  (or
   (when (and file-name
              (projectile-project-p))
     (let ((face (if active 'doom-modeline-buffer-path))
           (bracket-face (if active 'doom-modeline-bracket)))
       (concat
        (propertize "{" 'face bracket-face)
        (propertize (concat (aj/abbreviate-file-name (projectile-project-name)))
                    'face face)
        (propertize "} " 'face bracket-face))))
   ""))

(doom-modeline-def-segment aj/buffer-project-name
  "Displays `projectile-project-name'."
  (aj/formatted-buffer-project-name buffer-file-name (doom-modeline--active)))
```

This assumes the project never changes, and I'm okay with that. Also it's important to note that `defmemoize` doesn't work if the function returns `nil`, so I always return `""` instead.

**Comment by aaronjensen** [comment]
Another idea: what about allowing `buffer-info` to be the only thing that applies the inactive face? `doom-modeline-update-buffer-file-name` would only ever update w/ the active version and `buffer-info` would repropertize it w/ inactive. The only thing I don't know is if there are nested faces so that wouldn't really work for that.

**Comment by seagle0128** [comment]
Thanks, @aaronjensen ! I understand the scenario completely now, although I still cannot reproduce it in my local environment. In my understanding, it's an edge case, but I am looking at the codes and trying to find a solution.

**Comment by aaronjensen** [comment]
@seagle0128 your change appears to work for me so far. I'll let you know if I see the issue again. Thank you very much for the fix.

**Comment by seagle0128** [comment]
Last commit fixes this issue but breaks other case. I updated again.

**Comment by aaronjensen** [comment]
@seagle0128 it still appears to work for me with the new update. Thanks again.

**Comment by seagle0128** [comment]
Great to know! Thanks for the feedback, @aaronjensen !
