### ISSUE TITLE
Modeline icon contains misbehaving pixels

### ISSUE THREAD

**Issue by steven-lang** [seagle0128/doom-modeline#328]
**Describe**
The modeline icon on the far left sometimes shows weird pixels of a different color than the icon itself. This happens to multiple icons such as the folder icon, as well as mode indicators for evil-mode. The pixels appear, change location, and vanish again und an unreasonable pattern.

**Environment:**
 - OS and version: Linux
 - Emacs Version: 27.0.60
 - Configuration: Doom ([config](https://github.com/steven-lang/dotfiles/tree/master/configs/emacs/.doom.d))
 - Package version: Commit 0642f7107102e88fb8818da02e6612c6855537ff

**Additional context**
![Screenshot from 2020-04-04 13-00-14](https://user-images.githubusercontent.com/17625341/78427503-4b4f6600-7674-11ea-8d02-fd90f2b79016.png)
![Screenshot from 2020-04-04 13-00-00](https://user-images.githubusercontent.com/17625341/78427511-4be7fc80-7674-11ea-920a-d5654873d82c.png)
![Screenshot from 2020-04-04 13-01-01](https://user-images.githubusercontent.com/17625341/78427702-5a361880-7674-11ea-90cd-3093cea3c1f1.png)
![Screenshot from 2020-04-04 12-58-59](https://user-images.githubusercontent.com/17625341/78426754-1216f600-7674-11ea-8170-123b808e72cf.png)

**Comment by seagle0128** [comment]
Wired! Are you able to reproduce with the vanilla Emacs?

**Comment by steven-lang** [comment]
Ah, sorry for not giving a minimum working example:

```emacs-lisp
(eval-when-compile
  ;; Following line is not needed if use-package.el is in ~/.emacs.d
  (add-to-list 'load-path "~/use-package")
  (require 'use-package))

(use-package doom-modeline
  :ensure t
  :init (doom-modeline-mode 1))

(use-package evil
  :ensure t
  :init (evil-mode))

(use-package doom-themes
  :config
  ;; Global settings (defaults)
  (load-theme 'doom-one t))
```
Results in the above described behavior.

**Comment by seagle0128** [comment]
I tested on Windows 10, macOS Catalina, Manjora i3, Mint Linux. No this issue was observed. 
I suggest you try Emacs 26.3 or 28.0.50 with other WM and other themes.

**Comment by steven-lang** [comment]
That is weird indeed. Thanks for cross-testing tho! I was hoping that this has been observed somewhere else before. Feel free to close the issue, it's probably something on my side then.

**Comment by steven-lang** [comment]
@seagle0128 I've just found out that if I call `make-frame`, the issue disappears in the original frame and in the new frame as well. As soon as I close the new frame, the issue comes back again.

Does that give you any further clue on what might be causing this?

**Comment by seagle0128** [comment]
I think it might be caused by Emac, WM, or Graphic render/driver.

**Comment by connorhodes** [comment]
I had an issue similar to this and found [a workaround.](https://github.com/hlissner/doom-emacs/issues/3911#issuecomment-697697060) In my case, I was using a ".ttf" font and manually switching to the Nerd Font ".otf" version of the same font eliminated the issue. @steven-lang, I'm curious to see if this fixes your issue as well.

**Comment by steven-lang** [comment]
Thanks for the suggestion. I've applied your workaround but it did not resolve my issue.

**Comment by tiZero** [comment]
The misbehavior disappears if I remove the bold weight in the corresponding doom-modeline segments (as defined in `doom-modeline-core.el`). Namely, I added the following to my `config.el`:

```
(custom-set-faces!
  ;; Flycheck check symbol and sim-card symbol (right-hand side)
  '(doom-modeline-warning :inherit warning)
  '(doom-modeline-debug :inherit font-lock-doc-face :slant normal)

  ;; Insert/normal state (left-hand side)
  '(doom-modeline-evil-emacs-state :inherit font-lock-builtin-face)
  '(doom-modeline-evil-insert-state :inherit font-lock-keyword-face)
  '(doom-modeline-info :inherit success)
  )
```

**Comment by seagle0128** [comment]
@tiZero so it means it's a bug of emacs?

**Comment by tiZero** [comment]
@seagle0128 What do you mean?

**Comment by seagle0128** [comment]
You mentioned removing the bold weight of faces addressed the issue. But faces rendering is built in emacs. so it seems a bug of emacs itself.

**Comment by tiZero** [comment]
Ok. Anyway I'm runing Emacs 27.1 on Manjaro i3

**Comment by haluk** [comment]
I'm experiencing the same problem. Did you solve it?

**Comment by tiZero** [comment]
@haluk @0xConnorRhodes Following [this](https://github.com/hlissner/doom-emacs/issues/956) I fixed the issue changing `Xft.rgba: rgb` to `Xft.rgba: rgba` in my `.Xresources`.

**Comment by haluk** [comment]
@tiZero I dont' have this problem with GNU Emacs but gccemacs. I added `Xft.rgba: none` into `~/.Xresources` but I still have the same problem.

**Comment by yusi1** [comment]
> @haluk @0xConnorRhodes I fixed the issue setting `Xft.rgba: none` in my `.Xresources`.
This doesn't work for me on Emacs 30, the issue is back.
